### ISSUE TITLE
Tools & Weapons Models doesn't fit new texture

### ISSUE THREAD

**Issue by kasma360** [Faithful3D/1.16#10]
**Version name (1.16. - r1)**

**Describe the bug**
the model of the tools of faithful have changed and is no longer the same as that of minecraft 1.15

**Screenshots**
![2020-06-29_09 03 43](https://user-images.githubusercontent.com/62169857/85991924-712aa380-b9f4-11ea-857b-29635d821cfc.png)
![2020-06-29_09 03 48](https://user-images.githubusercontent.com/62169857/85991952-7d166580-b9f4-11ea-965b-55ff5e841801.png)
![2020-06-29_10 20 38](https://user-images.githubusercontent.com/62169857/85991958-80115600-b9f4-11ea-82e3-af31b0faafa1.png)
![2020-06-29_10 22 52](https://user-images.githubusercontent.com/62169857/85991964-81db1980-b9f4-11ea-8bb7-6ee1661d5c25.png)
![2020-06-29_10 23 55](https://user-images.githubusercontent.com/62169857/85991969-83a4dd00-b9f4-11ea-9f85-802599ea58c2.png)

I found this bug visible on the following objects: bow, shovel, axe and hoe

**Comment by Juknum** [comment]
fixed in 1.16.2 R1
