### ISSUE TITLE
Crimson and warped stem doesn't have the 3D model

### ISSUE THREAD

**Issue by Pomik108** [Faithful3D/1.16#11]
**Version: 1.16.1-r1**
Since the logs and the stems have a very similar texture, it'd make sense for them to use the new log model as well. That's not the case, however.

**To Reproduce**
1. Place down a stem.
2. It only uses the vanilla cube model.

**Screenshots**
![2020-06-29_18 26 18](https://user-images.githubusercontent.com/59484948/86031390-0dc16580-ba36-11ea-9034-7c8b5069e0ab.png)

**Additional context**
This is probably an oversight, so I reported it to alert the devs.

**Comment by Juknum** [comment]
They are not implemented yet, that's why
