### ISSUE TITLE
Bottle in inventory - missing glass 'shine/glint'

### ISSUE THREAD

**Issue by LetsTryThisAgain** [Faithful3D/1.16#13]
**Faithful+3D+-+1.16++1.16.1+-+R1**

**Describe the bug**
Bottles rendered in inventory are missing two sets of complimenting glints.

**To Reproduce**

1. `/give @s minecraft:potion`
2. Note how the bottle(s) are missing the white/light blue pixels that give the appearance of a 'shine/glint'
3. Turn off Faithful 3D resource pack
4. Note how the bottle(s) have the white/light blue pixels that give the appearance of a 'shine/glint'

**Expected behavior**
The bottle textures should remain visually the same between Faithful 32x and Faithful 3D.

**Screenshots**
![2020-07-01_09 06 47](https://user-images.githubusercontent.com/67689396/86247710-dc05e700-bb7a-11ea-86b6-033c1d70d3f6.png)

**Additional context**
_Slime Powered Minecarts are the best Minecarts!_ Keep on Keepin' on!

**Comment by Juknum** [comment]
Better without :)

**Comment by LetsTryThisAgain** [comment]
> 
> 
> Better without :)

Boo hiss :p
