### ISSUE TITLE
Chiseled Nether Bricks not rendering change

### ISSUE THREAD

**Issue by LetsTryThisAgain** [Faithful3D/1.16#14]
**Faithful+3D+-+1.16++1.16.1+-+R1**

**Describe the bug**
Chiseled Nether Bricks - while they have a 'model' file in the resource pack, show no change in game.

**To Reproduce**

1. /setblock ~ ~ ~ minecraft:chiseled_nether_bricks
2. Examine the block.
3. Turn off Faithful 3D resource pack
4. Note the lack of difference between with/without Faithful 3D resource pack.

**Expected behavior**
Faithful 3D resource pack should render the Chiseled Nether Brick different than the default.

**Screenshots**
![2020-07-01_10 07 28](https://user-images.githubusercontent.com/67689396/86253777-f8a61d00-bb82-11ea-8a5b-0251bc3b1e4d.png)

**EDIT** Note - the detail may be so subtle that on a dark version, it's near impossible to tell. (Is it the eyes and mouth of the skull? Could this be improved upon by deepening those aspects? Could this be improved upon by making the brick grout recessed?

**Additional context**
_Really curious what the 3D version will/should look like!_ Keep on Keepin' on!

**Comment by LetsTryThisAgain** [comment]
Note - the detail may be so subtle that on a dark version, it's near impossible to tell. (Is it the eyes and mouth of the skull?)

**Comment by RobertRR11** [comment]
The eyes and mouth of the skull are deeper. I'm probably going to edit the block a bit and make the skull stand out more.
