### ISSUE TITLE
Mossy stone brick wall and regular brick wall having no model + missing texture

### ISSUE THREAD

**Issue by Chiyko** [Faithful3D/1.16#16]
**Version name (ex : 1.16.1 - 20w27a)**

**Describe the bug**
Mossy stone brick walls and regular brick walls have no models, whereas all other wall models have textures and models.

**To Reproduce**
1. Get both walls or set them with a command
2. The walls will have missing textures

**Expected behavior**
The walls would render properly

**Screenshots**
![image](https://user-images.githubusercontent.com/67575110/86275560-90882300-bbe4-11ea-8efc-fb9669dabd51.png)

**Comment by RobertRR11** [comment]
I can't reproduce this issue. Do you have any other addon installed? Do you have the newest version of Faithful and Faithful 3D installed?

**Comment by Juknum** [comment]
Doesn't happen in Faithful 3D, can you tell us if you have any other resource pack? we doesn't modify at all wall in our pack
