### ISSUE TITLE
Bug texture faithful 3D

### ISSUE THREAD

**Issue by BaccaraShouko** [Faithful3D/1.16#24]
**Version name: 1.16 - 1.16.1 - R1**

**Describe the bug**
The edges of the trapdoors are in conflict.
It doesn't matter whether they are wood, iron or whatever, the bug is present.

**To Reproduce**
I just add faithful 32x, faithful 3D
and some addons and play.

**Expected behavior**
Just seeing the white / silver edge of the iron.

**Screenshots**
[Screen1](https://i.baccara-dev.xyz/w7sR2B0.png)

**Comment by Juknum** [comment]
Already Fixed on GitHub's version! Thanks!
