### ISSUE TITLE
Missing trapdoor side textures

### ISSUE THREAD

**Issue by kevindwitama** [Faithful3D/1.16#25]
Affects version 1.16 r1, possible more.

Trapdoor sides display the purple/black placeholder texture .

After some digging through the pack contents, it seems that the **textures/ctm/trapdoors** directory is missing all but the warped trapdoor front/side textures.

Can confirm that this is not a resource pack conflict as even with a fresh download from CurseForge and no other packs installed the same thing occurs.

Screenshots:

![2020-08-06_11 42 23](https://user-images.githubusercontent.com/10781720/89492034-d5ead200-d7da-11ea-855a-867a40dbdfd9.png)

![trapdoor](https://user-images.githubusercontent.com/10781720/89492046-dc794980-d7da-11ea-9569-f116bea17240.png)

**Comment by Juknum** [comment]
Already fixed on GitHub’s version

**Comment by RobertRR11** [comment]
Not related to the issue, but could I maybe know what your shader is? I really like it.

**Comment by kevindwitama** [comment]
> 
> 
> Not related to the issue, but could I maybe know what your shader is? I really like it.

Complementary shaders with a custom profile.
