### ISSUE TITLE
Issue with 3D Texture

### ISSUE THREAD

**Issue by ItzNathaniel** [Faithful3D/1.16#26]
**Version name Mast Branch**

**Describe the bug**
Yo these textures wack.

**To Reproduce**
I don't think there is none.

**Expected behavior**
These shouldn't be here.

**Screenshots**
![image](https://user-images.githubusercontent.com/11449808/95543691-166af580-09ae-11eb-8ac3-2bd144737d3c.png)

**Comment by Juknum** [comment]
Wtf

**Comment by RobertRR11** [comment]
Can you maybe tell if you're using any addons? And if yes, then which ones?

**Comment by RobertRR11** [comment]
Just found that it happens because of the connected textures in Outlined Ores.
You would need to disable connected textures till this issue is fixed: Video Settings/Quality/Connected Textures

**Comment by ItzNathaniel** [comment]
> Just found that it happens because of the connected textures in Outlined Ores.
> You would need to disable connected textures till this issue is fixed: Video Settings/Quality/Connected Textures

Thank you! :)
