### ISSUE TITLE
Oak trapdoor shows a missing model

### ISSUE THREAD

**Issue by Pomik108** [Faithful3D/1.16#7]
**Version: 1.16.1-r1**

The title says it all. The item model works properly, but as soon as you place the trapdoor down it shows the purple-black missing model cube. This applies too all of the trapdoor's blockstates as far as I know.

**How to reproduce**
1. Get an oak trapdoor
2. Place it down
3. You can see the missing model

**Expected behaviour**
The oak trapdoor should show its 3D model.

**Screenshots**
![2020-06-27_17 57 08](https://user-images.githubusercontent.com/59484948/85927654-da50d080-b8a7-11ea-9df3-8fbf8a326245.png)

**Additional context**
I've tried looking into it, and it looks like it's a blockstate issue. At first i thought there were just some missing brackets, but then I tried adding them in but nothing changed. This might also be caused by some other add-on I'm using – I'll test this without any other add-ons soon.

**Comment by Pomik108** [comment]
Okay nevermind, it's caused by some other add-on; the trapdoor works properly when i disable all other add-ons. You can safely disregard this

**Comment by Juknum** [comment]
Can you find wich addon it is? 🤔

**Comment by Pomik108** [comment]
It was my custom addon. I've had some old blockstates there which I forgot about, and they messed with the models.

**Comment by Juknum** [comment]
Closing this issue while your addon isn't public :)
