### ISSUE TITLE
Missing textures on trapdoor sides

### ISSUE THREAD

**Issue by RobertRR11** [Faithful3D/1.16#8]
**Version name (ex : 1.15.2 - r2)**
1.16.1 - r1

**Describe the bug**
Placing a trapdoor causes the side texture to be missing. Using the newest Faithful 3D and Faithful version. Also happens when holding it.
Small addition: the warped trapdoor doesn't have this problem

**To Reproduce**
1. get any trapdoor
2. place any trapdoor

**Expected behavior**
Having no error textures

**Screenshots**
![2020-06-27_19 36 31](https://user-images.githubusercontent.com/57044042/85928567-3585c180-b8ae-11ea-94c7-9c9f22307521.png)
![2020-06-27_19 44 10](https://user-images.githubusercontent.com/57044042/85928621-a0cf9380-b8ae-11ea-950e-32e1cf940284.png)

**Comment by Pomik108** [comment]
This can be fixed easily by editing the model, just change the `ctm` in the texture path to `custom`

**Comment by RobertRR11** [comment]
nothing changed after doing it

**Comment by Pomik108** [comment]
huh

**Comment by Juknum** [comment]
Which version of Faithful did you use?

**Comment by RobertRR11** [comment]
the newest on github ¯\_(ツ)_/¯ 1.16

**Comment by Pomik108** [comment]
hmmm i think it could be fixed by changing `ctm` into `custom\trapdoors` maybe?
